version: 2.1
orbs: 
  matlab: mathworks/matlab@1 
jobs:
  test:
    machine:
      image: ubuntu-2004:current 
    parallelism: 2
    steps:
      - checkout
      - matlab/install
      - matlab/run-tests:
          test-results-junit: test-results/matlab/results.xml
      - store_test_results:
          path: test-results
      - run:
          name: Debug Test Files
          command: |
            TestFiles=$(circleci tests glob 'tests/**/*.m'|  circleci tests split --split-by=timings)
            echo "Test files found:"
            echo "$TestFiles"
workflows:
  version: 2
  filesize:
    jobs:
      - test
